version: '3'
services:
  primary:
    build:
      context: .
    ports:
     - "5000:5000"
    image: "mqamouser/workshop:alpha"
  secondary:
    build:
      context: .
    ports:
     - "5001:5000"
    image: "mqamouser/workshop:beta"
  tertiary:
    build:
      context: .
    ports:
     - "5002:5000"
    image: "mqamouser/workshop:charlie"